name: expense_tracker_app
description: "A modern Expense Tracker app built using Flutter."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  cupertino_icons: ^1.0.8

  # UI & Styling
  google_fonts: ^6.1.0  # Modern fonts
  fl_chart: ^0.66.0  # For bar charts
  flutter_svg: ^2.0.9  # For vector icons (optional)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  
  